// 
//    This code was generated by EtwEventTypeGen.exe 
//

using System;

namespace Microsoft.Etw.Microsoft_Windows_HttpService
{
    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 88, 0)]
    public class ThreadGone : SystemEvent
    {
        [EventField("win:AnsiString")]
        public string PoolType { get; set; }

        [EventField("win:UInt16")]
        public ushort ActivePools { get; set; }

        [EventField("win:UInt8")]
        public byte ThreadCount { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 87, 0)]
    public class ThreadPoolTrim : SystemEvent
    {
        [EventField("win:AnsiString")]
        public string PoolType { get; set; }

        [EventField("win:UInt16")]
        public ushort ActivePools { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 86, 0)]
    public class ThreadReady : SystemEvent
    {
        [EventField("win:AnsiString")]
        public string PoolType { get; set; }

        [EventField("win:UInt16")]
        public ushort ActivePools { get; set; }

        [EventField("win:UInt8")]
        public byte ThreadCount { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 85, 0)]
    public class ThreadPoolExtension : SystemEvent
    {
        [EventField("win:AnsiString")]
        public string PoolType { get; set; }

        [EventField("win:UInt16")]
        public ushort ActivePools { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 84, 0)]
    public class UsePolicyBasedQoSFlow : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong Connection { get; set; }

        [EventField("win:Pointer")]
        public ulong FlowHandle { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 83, 0)]
    public class ChannelBindPerResponseConfig : SystemEvent
    {
        [EventField("win:AnsiString")]
        public string ReplaceConfigOf { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 82, 0)]
    public class ChannelBindConfigCapture : SystemEvent
    {
        [EventField("win:UInt8")]
        public byte Hardening { get; set; }

        [EventField("win:UInt32")]
        public uint Flags { get; set; }

        [EventField("win:UInt32")]
        public uint ServiceNameCount { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 81, 0)]
    public class ServiceBindCheckComplete : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong ConnectionId { get; set; }

        [EventField("win:Pointer")]
        public ulong SecContextL { get; set; }

        [EventField("win:Pointer")]
        public ulong SecContextH { get; set; }

        [EventField("win:UInt32")]
        public uint SecStatus { get; set; }

        [EventField("win:UnicodeString")]
        public string Target { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 80, 0)]
    public class ChannelBindAscParams : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong ConnectionId { get; set; }

        [EventField("win:UInt32")]
        public uint NoBindBuffers { get; set; }

        [EventField("win:UInt32")]
        public uint SecFlags { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 79, 0)]
    public class FlatCacheRangeSend : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong CacheEntryPtr { get; set; }

        [EventField("win:UInt64")]
        public ulong Range1Start { get; set; }

        [EventField("win:UInt64")]
        public ulong Range1End { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 78, 0)]
    public class MergeSlicesToCache : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong CacheEntryPtr { get; set; }

        [EventField("win:UInt32")]
        public uint NofSlicesToMerge { get; set; }

        [EventField("win:UInt32")]
        public uint NofSlicesInCache { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 77, 0)]
    public class CachedSlicesMatchContent : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:Pointer")]
        public ulong CacheEntryPtr { get; set; }

        [EventField("win:UInt32")]
        public uint NumberOfSlices { get; set; }

        [EventField("win:UInt32")]
        public uint SliceIndex1 { get; set; }

        [EventField("win:UInt32")]
        public uint SliceIndex2 { get; set; }

        [EventField("win:UInt32")]
        public uint NumberOfRanges { get; set; }

        [EventField("win:UInt64")]
        public ulong Range1Start { get; set; }

        [EventField("win:UInt64")]
        public ulong Range1End { get; set; }

        [EventField("win:UInt64")]
        public ulong Range2Start { get; set; }

        [EventField("win:UInt64")]
        public ulong Range2End { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 76, 0)]
    public class SendSliceCacheContent : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:Pointer")]
        public ulong CacheEntryPtr { get; set; }

        [EventField("win:UInt32")]
        public uint NumberOfSlices { get; set; }

        [EventField("win:UInt32")]
        public uint SliceIndex1 { get; set; }

        [EventField("win:UInt32")]
        public uint SliceIndex2 { get; set; }

        [EventField("win:UInt32")]
        public uint NumberOfRanges { get; set; }

        [EventField("win:UInt64")]
        public ulong Range1Start { get; set; }

        [EventField("win:UInt64")]
        public ulong Range1End { get; set; }

        [EventField("win:UInt64")]
        public ulong Range2Start { get; set; }

        [EventField("win:UInt64")]
        public ulong Range2End { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 75, 0)]
    public class BeginBuildingSlices : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt32")]
        public uint NumberOfSlices { get; set; }

        [EventField("win:UInt32")]
        public uint SliceIndex1 { get; set; }

        [EventField("win:UInt32")]
        public uint SliceIndex2 { get; set; }

        [EventField("win:UInt32")]
        public uint NumberOfRanges { get; set; }

        [EventField("win:UInt64")]
        public ulong Range1Start { get; set; }

        [EventField("win:UInt64")]
        public ulong Range1End { get; set; }

        [EventField("win:UInt64")]
        public ulong Range2Start { get; set; }

        [EventField("win:UInt64")]
        public ulong Range2End { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 74, 0)]
    public class ResponseRangeProcessingOK : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt64")]
        public ulong ContentBytes { get; set; }

        [EventField("win:UInt32")]
        public uint NumberOfRanges { get; set; }

        [EventField("win:UInt64")]
        public ulong Range1Start { get; set; }

        [EventField("win:UInt64")]
        public ulong Range1End { get; set; }

        [EventField("win:UInt64")]
        public ulong Range2Start { get; set; }

        [EventField("win:UInt64")]
        public ulong Range2End { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 73, 0)]
    public class ConnectionFlowFailed : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong Connection { get; set; }

        [EventField("win:Pointer")]
        public ulong FlowHandle { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 72, 0)]
    public class RequestAssociatedToConfigurationFlow : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong FlowHandle { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 71, 0)]
    public class SetConnectionFlow : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong Connection { get; set; }

        [EventField("win:Pointer")]
        public ulong FlowHandle { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 70, 0)]
    public class FlowInitFailed : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint Bandwidth { get; set; }

        [EventField("win:UInt32")]
        public uint PeakBandwidth { get; set; }

        [EventField("win:UInt32")]
        public uint BurstSize { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 69, 0)]
    public class CachedResponseFlowInit : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong FlowHandle { get; set; }

        [EventField("win:UInt32")]
        public uint Bandwidth { get; set; }

        [EventField("win:UInt32")]
        public uint PeakBandwidth { get; set; }

        [EventField("win:UInt32")]
        public uint BurstSize { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 68, 0)]
    public class UserResponseFlowInit : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong FlowHandle { get; set; }

        [EventField("win:UInt32")]
        public uint Bandwidth { get; set; }

        [EventField("win:UInt32")]
        public uint PeakBandwidth { get; set; }

        [EventField("win:UInt32")]
        public uint BurstSize { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 67, 0)]
    public class HotAddProcSucceeded : SystemEvent
    {
        [EventField("win:UInt8")]
        public byte NewProcNumber { get; set; }

        [EventField("win:AnsiString")]
        public string Comment { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 66, 0)]
    public class HotAddProcFailed : SystemEvent
    {
        [EventField("win:UInt8")]
        public byte NewProcNumber { get; set; }

        [EventField("win:AnsiString")]
        public string ReasonString { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 65, 0)]
    public class RequestCancelled : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:AnsiString")]
        public string Reason { get; set; }

        [EventField("win:UnicodeString")]
        public string RequestQueueName { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 64, 0)]
    public class RequestRejected : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:AnsiString")]
        public string Reason { get; set; }

        [EventField("win:UnicodeString")]
        public string RequestQueueName { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 63, 0)]
    public class SslSealMsg : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }

        [EventField("win:UInt32")]
        public uint SecStatus { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 62, 0)]
    public class SslAsc : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }

        [EventField("win:UInt32")]
        public uint SecStatus { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 61, 0)]
    public class SslEndpointConfigNotFound : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }

        [EventField("win:UInt32")]
        public uint AddressLength { get; set; }

        [EventField("win:Binary")]
        public byte[] Address { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 60, 0)]
    public class SslQueryConnInfoFailed : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }

        [EventField("win:UInt32")]
        public uint SecStatus { get; set; }

        [EventField("win:AnsiString")]
        public string Detail { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 59, 0)]
    public class SslUnsealMsg : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }

        [EventField("win:UInt32")]
        public uint SecStatus { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 58, 0)]
    public class SslDisconnReq : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 57, 0)]
    public class SslDisconnEvent : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 56, 0)]
    public class SslEndpointCreationFailed : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong EndpointConfigObj { get; set; }

        [EventField("win:UInt32")]
        public uint SecStatus { get; set; }

        [EventField("win:AnsiString")]
        public string Detail { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 53, 0)]
    public class ConnTimedOut : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong ConnectionId { get; set; }

        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }

        [EventField("win:AnsiString")]
        public string Timer { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 52, 0)]
    public class ParseRequestFailed : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint Status { get; set; }

        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:AnsiString")]
        public string Reason { get; set; }

        [EventField("win:UInt32")]
        public uint ErrorCode { get; set; }

        [EventField("win:UInt32")]
        public uint HintLength { get; set; }

        [EventField("win:Binary")]
        public byte[] HintData { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 51, 0)]
    public class LogFileWrite : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint Status { get; set; }

        [EventField("win:Pointer")]
        public ulong Handle { get; set; }

        [EventField("win:UInt32")]
        public uint Type { get; set; }

        [EventField("win:UInt32")]
        public uint Group { get; set; }

        [EventField("win:UInt32")]
        public uint Format { get; set; }

        [EventField("win:AnsiString")]
        public string ResType { get; set; }

        [EventField("win:UInt32")]
        public uint SiteId { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 50, 0)]
    public class LogFileCreate : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong Handle { get; set; }

        [EventField("win:UInt32")]
        public uint Type { get; set; }

        [EventField("win:UInt32")]
        public uint Group { get; set; }

        [EventField("win:UInt32")]
        public uint Format { get; set; }

        [EventField("win:UnicodeString")]
        public string Filename { get; set; }

        [EventField("win:UInt32")]
        public uint SiteId { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 49, 0)]
    public class LogFileCreateFailed : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint Status { get; set; }

        [EventField("win:UInt32")]
        public uint Type { get; set; }

        [EventField("win:UInt32")]
        public uint Group { get; set; }

        [EventField("win:UInt32")]
        public uint Format { get; set; }

        [EventField("win:UnicodeString")]
        public string Filename { get; set; }

        [EventField("win:UInt32")]
        public uint SiteId { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 48, 0)]
    public class LoggingConfig : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint Present { get; set; }

        [EventField("win:UInt32")]
        public uint Type { get; set; }

        [EventField("win:UInt32")]
        public uint Group { get; set; }

        [EventField("win:UInt32")]
        public uint Format { get; set; }

        [EventField("win:UnicodeString")]
        public string Directory { get; set; }

        [EventField("win:UnicodeString")]
        public string Software { get; set; }

        [EventField("win:UInt32")]
        public uint SiteId { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 47, 0)]
    public class LoggingConfigFailed : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint Status { get; set; }

        [EventField("win:UInt32")]
        public uint Type { get; set; }

        [EventField("win:UInt32")]
        public uint Group { get; set; }

        [EventField("win:UnicodeString")]
        public string Directory { get; set; }

        [EventField("win:UnicodeString")]
        public string Software { get; set; }

        [EventField("win:UInt32")]
        public uint SiteId { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 46, 0)]
    public class QosFlowSetReset : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong ConnectionId { get; set; }

        [EventField("win:UInt32")]
        public uint Bandwidth { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 45, 0)]
    public class AuthCacheEntryFreed : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong AccessTokenOrHandle { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 44, 0)]
    public class AuthCacheEntryAdded : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong ConnectionId { get; set; }

        [EventField("win:AnsiString")]
        public string AuthCacheType { get; set; }

        [EventField("win:Pointer")]
        public ulong AccessTokenOrHandle { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 43, 0)]
    public class SspiCall : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong ConnectionId { get; set; }

        [EventField("win:AnsiString")]
        public string AuthType { get; set; }

        [EventField("win:UInt32")]
        public uint SecStatus { get; set; }

        [EventField("win:UInt32")]
        public uint AuthStatus { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 41, 0)]
    public class SslAcceptStreamData : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint DataLength { get; set; }

        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 40, 0)]
    public class SslDlvrdStreamData : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint DataLength { get; set; }

        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 39, 0)]
    public class SslRcvdRawData : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint DataLength { get; set; }

        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 38, 0)]
    public class SslRcvClientCertFailed : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint Status { get; set; }

        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 37, 0)]
    public class SslInititateSslRcvClientCert : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 36, 0)]
    public class SslHandshakeComplete : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint Status { get; set; }

        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 35, 0)]
    public class SslInitiateHandshake : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 34, 0)]
    public class SslConnEvent : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 33, 0)]
    public class RemAllUrls : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong UrlGroupId { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 32, 0)]
    public class RemUrl : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong UrlGroupId { get; set; }

        [EventField("win:UnicodeString")]
        public string Url { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 31, 0)]
    public class AddUrl : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong UrlGroupId { get; set; }

        [EventField("win:UnicodeString")]
        public string Url { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 30, 0)]
    public class ChgReqQueueProp : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint Property { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 29, 0)]
    public class ChgSrvSesProp : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint Property { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 28, 0)]
    public class ChgUrlGrpProp : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint Property { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 27, 0)]
    public class FlushedCache : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string Uri { get; set; }

        [EventField("win:UInt16")]
        public ushort StatusCode { get; set; }

        [EventField("win:AnsiString")]
        public string Verb { get; set; }

        [EventField("win:UInt32")]
        public uint HeaderLength { get; set; }

        [EventField("win:UInt32")]
        public uint ContentLength { get; set; }

        [EventField("win:UInt64")]
        public ulong ExpirationTime { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 26, 0)]
    public class AddCacheEntryFailed : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string UrlBuffer { get; set; }

        [EventField("win:UInt32")]
        public uint ErrorStatus { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 25, 0)]
    public class AddedCacheEntry : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string Uri { get; set; }

        [EventField("win:UInt16")]
        public ushort StatusCode { get; set; }

        [EventField("win:AnsiString")]
        public string Verb { get; set; }

        [EventField("win:UInt32")]
        public uint HeaderLength { get; set; }

        [EventField("win:UInt32")]
        public uint ContentLength { get; set; }

        [EventField("win:UInt64")]
        public ulong ExpirationTime { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 24, 0)]
    public class ConnCleanup : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 23, 0)]
    public class ConnClose : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }

        [EventField("win:UInt32")]
        public uint Abortive { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 22, 0)]
    public class ConnIdAssgn : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt64")]
        public ulong ConnectionId { get; set; }

        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 21, 0)]
    public class ConnConnect : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong ConnectionObj { get; set; }

        [EventField("win:UInt32")]
        public uint LocalAddrLength { get; set; }

        [EventField("win:Binary")]
        public byte[] LocalAddr { get; set; }

        [EventField("win:UInt32")]
        public uint RemoteAddrLength { get; set; }

        [EventField("win:Binary")]
        public byte[] RemoteAddr { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 20, 0)]
    public class CreatedSslCred : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong EndpointConfigObj { get; set; }

        [EventField("win:UInt32")]
        public uint AddressLength { get; set; }

        [EventField("win:Binary")]
        public byte[] Address { get; set; }

        [EventField("win:UInt32")]
        public uint CertHashLength { get; set; }

        [EventField("win:Binary")]
        public byte[] CertHash { get; set; }

        [EventField("win:UnicodeString")]
        public string CertStoreName { get; set; }

        [EventField("win:UInt32")]
        public uint CertCheckMode { get; set; }

        [EventField("win:UInt32")]
        public uint RevokeFreshnessTime { get; set; }

        [EventField("win:UInt32")]
        public uint RevokeRetrievalTime { get; set; }

        [EventField("win:UInt32")]
        public uint Flags { get; set; }

        [EventField("win:UnicodeString")]
        public string CtlId { get; set; }

        [EventField("win:UnicodeString")]
        public string CtlStoreName { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 19, 0)]
    public class ReadIpListEntry : SystemEvent
    {
        [EventField("win:UInt32")]
        public uint IpAddrLength { get; set; }

        [EventField("win:Binary")]
        public byte[] IpAddress { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 18, 0)]
    public class ResvUrl : SystemEvent
    {
        [EventField("win:UnicodeString")]
        public string Url { get; set; }

        [EventField("win:UInt32")]
        public uint ReserveStatus { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 17, 0)]
    public class CachedNotModified : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong RequestObj { get; set; }

        [EventField("win:UInt32")]
        public uint SiteId { get; set; }

        [EventField("win:UInt32")]
        public uint BytesSent { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 16, 0)]
    public class SrvdFrmCache : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong RequestObj { get; set; }

        [EventField("win:UInt32")]
        public uint SiteId { get; set; }

        [EventField("win:UInt32")]
        public uint BytesSent { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 15, 0)]
    public class SndError : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:AnsiString")]
        public string Reason { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 14, 0)]
    public class LastSndError : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt16")]
        public ushort HttpStatus { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 13, 0)]
    public class ZeroSend : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt16")]
        public ushort HttpStatus { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 12, 0)]
    public class FastSend : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt16")]
        public ushort HttpStatus { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 11, 0)]
    public class CachedAndSend : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt16")]
        public ushort HttpStatus { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 10, 0)]
    public class SendComplete : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt16")]
        public ushort HttpStatus { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 9, 0)]
    public class FastRespLast : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 8, 0)]
    public class FastResp : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt64")]
        public ulong ConnectionId { get; set; }

        [EventField("win:UInt16")]
        public ushort StatusCode { get; set; }

        [EventField("win:AnsiString")]
        public string Verb { get; set; }

        [EventField("win:UInt32")]
        public uint HeaderLength { get; set; }

        [EventField("win:UInt16")]
        public ushort EntityChunkCount { get; set; }

        [EventField("win:UInt32")]
        public uint CachePolicy { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 7, 0)]
    public class RecvBodyLast : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 6, 0)]
    public class RecvBody : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt64")]
        public ulong ConnectionId { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 5, 0)]
    public class RecvRespLast : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 4, 0)]
    public class RecvResp : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt64")]
        public ulong ConnectionId { get; set; }

        [EventField("win:UInt16")]
        public ushort StatusCode { get; set; }

        [EventField("win:AnsiString")]
        public string Verb { get; set; }

        [EventField("win:UInt32")]
        public uint HeaderLength { get; set; }

        [EventField("win:UInt16")]
        public ushort EntityChunkCount { get; set; }

        [EventField("win:UInt32")]
        public uint CachePolicy { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 3, 0)]
    public class Deliver : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong RequestObj { get; set; }

        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt32")]
        public uint SiteId { get; set; }

        [EventField("win:UnicodeString")]
        public string RequestQueueName { get; set; }

        [EventField("win:UnicodeString")]
        public string Url { get; set; }

        [EventField("win:UInt32")]
        public uint Status { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 2, 0)]
    public class Parse : SystemEvent
    {
        [EventField("win:Pointer")]
        public ulong RequestObj { get; set; }

        [EventField("win:UInt32")]
        public uint HttpVerb { get; set; }

        [EventField("win:UnicodeString")]
        public string Url { get; set; }
    }

    [ManifestEvent("{dd5ef90a-6398-47a4-ad34-4dcecdef795f}", 1, 0)]
    public class RecvReq : SystemEvent
    {
        [EventField("win:UInt64")]
        public ulong RequestId { get; set; }

        [EventField("win:UInt64")]
        public ulong ConnectionId { get; set; }

        [EventField("win:UInt32")]
        public uint RemoteAddrLength { get; set; }

        [EventField("win:Binary")]
        public byte[] RemoteAddr { get; set; }
    }

}
